parameters:
  human_verification_enabled: '%env(bool:HUMAN_VERIFICATION_ENABLED)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Service\NullHumanVerificationService:
    arguments:
      $enabled: '%human_verification_enabled%'

  App\Service\HumanVerificationInterface:
    alias: App\Service\NullHumanVerificationService

  App\EventListener\ApiExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception }
